### ISSUE TITLE
Define the Design of our App

### ISSUE THREAD

**Issue by zachmandeville** [zachmandeville/show-me-the-money#5]

**Comment by steve-dev90** [comment]
Hi there,

Minimum number of pages 
Use of drop downs
Common headers and footers

![img-1788](https://user-images.githubusercontent.com/34639502/39558491-21373678-4ee3-11e8-825a-ca06f3fc8c7d.JPG)
![img-1789](https://user-images.githubusercontent.com/34639502/39558508-3e9b6c7a-4ee3-11e8-8ffa-2b0f92c5c904.JPG)

**Comment by steve-dev90** [comment]
Updated with story board people

![img-1790](https://user-images.githubusercontent.com/34639502/39559111-f3e68412-4ee7-11e8-9bcb-dce97099726e.JPG)
